@rem Placeholder wrapper script (Windows).
@rem
@rem The real Windows `gradlew.bat` is generated by Gradle. After
@rem cloning this template, run:
@rem
@rem   gradle wrapper --gradle-version 8.9
@rem
@rem to regenerate `gradlew`, `gradlew.bat`, and `gradle-wrapper.jar`.
@echo gradlew.bat placeholder. Run 'gradle wrapper --gradle-version 8.9' to regenerate.
@exit /b 1
